name: Rust

on:
  push:
    branches: [ main, cryptolab-phase-2 ]
  pull_request:
    branches: [ main, cryptolab-phase-2 ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: cryptolab-web-server
        path: |
          target/release/cryptolab-backend
